### ISSUE TITLE
Add `viewBox` attribute to root SVG element

### ISSUE THREAD

**Issue by Gazook89** [ushelp/EasyQRCodeJS#92]
Right now it doesn't seem like there is any way to set a viewBox for the SVG render, so it makes it difficult to resize the SVG with CSS.  Possibly this is my shortcoming with CSS, but I do know that it's at least a little easier if there is a viewBox on the SVG.

I added a line to the script, right in the part that defines the root `svg` element, shown below:

https://github.com/ushelp/EasyQRCodeJS/blob/e513316fe390c3c29bb06ab9ff0dbff25f9be0c4/src/canvas2svg.js#L253-L258

```js
this.__root.setAttribute("viewBox",`0 0 ${this.width} ${this.height}`)
```

And it works for me to now use CSS like this to set width/height and get proper scaling (without setting an absolute px value):

```css
.qr {   							// container
	width: 50%;
	max-width: 100px;
	& svg {
		width: 100%;
		height: 100%;
	}
}
```
